Fix for #91, #93.  Branched from upstream with rebase again (#112)
buildrs/Share pull request #120
Opened 2022-02-21 17:30 UTC by OlegMoshkovich

-Add new favicon

2022-02-22 14:14 UTC, OlegMoshkovich commented
@pablo-mayrgundter PTAL!

2022-02-22 16:01 UTC, OlegMoshkovich commented
@pablo-mayrgundter  
PTAL!

2022-02-22 16:38 UTC, pablo-mayrgundter requested changes
Can't wait :). Mostly just spaces

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Components/AboutPanel.jsx
> +  const [open, setOpen]=useState(true)
const [open,setOpen] = useState(true)

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Components/AboutPanel.jsx
> +        <IconButton onClick = {()=>setOpen(!open)}>
```
 <IconButton onClick={() => setOpen(!open)}>
```

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Components/AboutPanel.jsx
> +          <About className = {classes.icon}/>
```
<About className={classes.icon}/>
```

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Components/BaseGroup.jsx
> + */
```
/**
 * Base group contains Settings, ModelUpload, About
 * @param {Function} fileOpen opens a file dialog for new model upload
 * @param {Number} offsetTop
 * @return {Object} React component.
 */
```

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Components/ItemPanel.jsx
>  import {makeStyles} from '@mui/styles'
Please move this down to after default imports for @mui

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Components/ItemPanel.jsx
> +  console.log('open', open)
remove

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Components/ItemPanel.jsx
> +export default function ItemPanelButton({model, element, topOffset, toggle, open}) {
add @param docs for new params, and I think better names.. it's not clear what's being toggled or opened.. this component or something from the caller?

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Components/SearchBar.jsx
> +        {showNavPanel?<Close className={classes.icon}/>:<Hamburger className={classes.icon}/>}
```
{showNavPanel ? <Close className={classes.icon}/> : <Hamburger className={classes.icon}/>}
```

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Containers/CadView.jsx
> +              showNavPanel = {showNavPanel}
```
showNavPanel={showNavPanel}
```

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Containers/CadView.jsx
> +          open = {showItemPanel}
```
open={showItemPanel}
```

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Containers/CadView.jsx
> +          toggle={()=>setShowItemPanel(!showItemPanel)}
Next lines as well, spaces around arrow
```
() => ...
```

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Containers/CadView.jsx
> +        <div className={showItemPanel?classes.iconGroupOpen:classes.iconGroup}>
spaces around operators

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Containers/CadView.jsx
>              placeCutPlane={()=>placeCutPlane()}
spaces around arrows

2022-02-22 16:38 UTC, pablo-mayrgundter commented on src/Containers/CadView.jsx
> +        <LogoDark className = {classes.logo}/>
no spaces around =, and on next line spaces around ops

2022-02-22 18:13 UTC, OlegMoshkovich commented
PTAL!

2022-02-22 18:18 UTC, pablo-mayrgundter requested changes

2022-02-22 18:18 UTC, pablo-mayrgundter commented on src/Components/ItemPanel.jsx
> +export default function ItemPanelButton({model, element, topOffset, setShowitempanel}) {
use the same casing as the original var, so setShowItemPanel

2022-02-22 18:18 UTC, pablo-mayrgundter commented on src/Components/ItemPanel.jsx
> +        setShowitempanel()
Ah, looks like there's a name conflict.. let's discuss

2022-02-22 18:18 UTC, pablo-mayrgundter commented on src/Components/ItemProperties.jsx
> +      }
Almost, move operators to front of line like in my example

2022-02-22 18:18 UTC, pablo-mayrgundter commented on src/Components/ItemPropertiesDrawer.jsx
> +          <Close className={classes.close} onClick = {onClose}/>
space

2022-02-22 18:18 UTC, pablo-mayrgundter commented on src/Components/ShortcutsPanel.jsx
> +      </IconButton>
ops at beginning of line

2022-02-23 11:33 UTC, OlegMoshkovich commented
PTAL!

2022-02-23 11:43 UTC, merged