Update theme
buildrs/Share pull request #92
Opened 2022-02-03 15:44 UTC by OlegMoshkovich

2022-02-03 16:19 UTC, OlegMoshkovich commented
https://olegmoshkovich.github.io/Share/share/v/p/tinyhouse.ifc

2022-02-04 13:54 UTC, pablo-mayrgundter commented on src/Components/AppsPanel.jsx
> +const AppsControl = ({offsetTop}) => {
Per my comments in discord, I think we should use function syntax, and directly export instead of export at bottom of page.

2022-02-04 14:17 UTC, pablo-mayrgundter requested changes
Please add unit tests for new components.. see my mockRoutes helper.. at very least, just need to add the component to a mockRoute and unit test that it's actually displayed.

In general let's use these code formatting reqs for any files we touch:
  - remove semi-colons from imports
  - move {} imports after default imports
  - double line between top-level defs, e.g. between import and first function
  - move useStyles to end; default export should be first after import
  - convert const arrow to function
  - move inline styles to useStyles section

2022-02-04 14:17 UTC, pablo-mayrgundter commented on src/Components/AppsPanel.jsx
> +    "& svg": {
[👍](https://emojipedia.org/thumbs-up/)

2022-02-04 14:17 UTC, pablo-mayrgundter commented on src/Components/DropDown.jsx
> +
double line between top-level definitions.

2022-02-04 14:17 UTC, pablo-mayrgundter commented on src/Components/DropDown.jsx
> +import * as React from 'react';
import { useState }

2022-02-04 14:17 UTC, pablo-mayrgundter commented on src/Components/DropDownToolbar.jsx
> +const BootstrapInput = styled(InputBase)(({ theme }) => ({
move to end and double-space between top-level defs.

2022-02-04 14:17 UTC, pablo-mayrgundter commented on src/Components/DropDownToolbar.jsx
> +export default function MultipleSelect() {
[👍](https://emojipedia.org/thumbs-up/)

double-line between

2022-02-04 14:17 UTC, pablo-mayrgundter commented on src/Components/ItemProperties.jsx
> +              <div key={ndx} className={classes.section}>
why div?  lists should be preferred to for accessibility/tabbing behavior

2022-02-04 14:17 UTC, pablo-mayrgundter commented on src/Components/ItemPropertiesDrawer.jsx
>  });
pls convert to export default function ItemPropertiesDrawer ...

2022-02-04 14:17 UTC, pablo-mayrgundter commented on src/Components/SearchBar.jsx
>  const useStyles = makeStyles({
move down

2022-02-04 14:17 UTC, pablo-mayrgundter commented on src/Components/SnackbarMessage.jsx
>        autoHideDuration={6000}
(sorry for comment down here.. gh won't let me make file comment...)

pls move useStyles to end, convert const arrow to function and move styles from inline to useStyles section.

2022-02-04 14:17 UTC, pablo-mayrgundter commented on src/Components/Toggle.jsx
> +const Toggle = styled(Switch)(({ theme }) => ({
(sorry for comment down here.. gh won't let me make file comment...)

pls move useStyles to end, convert const arrow to function and move styles from inline to useStyles section.

2022-02-10 14:23 UTC, closed without merging